name: Charlee
favicon: null
layout_spectrum: 0.16749186511151493
typography_spectrum: 0.5933434353210032
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.11220338311977684
  lightness: 0.35723738349042833
  saturation: 0.576493886532262
  rhythmicContrast: 0.34356959350407124
purpose: []
